Add firebase sign up with email and password
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k05-t01 pull request #13
Opened 2021-07-06 15:33 UTC by carloseag1609

# Description
What did you implemented/Why did you implemented this:
 - I've created the file firebaseSignIn.js in a new helpers folder. It exports a function which creates a new user on firebase.
 - I've fixed the two checkbox components in SignUp screen. Why? The checkboxes didn't work correctly (never checks or unchecks) and one of them didn't correspond with the form validations, so I fixed it.
 - I've fixd  the Yup validation schema with a valid regular expression for the password. Why? The regular expression for the password validation in the schema was a string, so I changed it to a valid regular expression.
 - I've added a new "loading" state. Why? When the form is submitted and called the function that creates the new user, it takes some time, so I added a new state (loading) which indicates if the user creation is loading or finished.

2021-07-06 15:42 UTC, cortezroberto reviewed
It's ok.

2021-07-06 15:44 UTC, yovanha submitted a review, later dismissed
Great!

2021-07-06 16:30 UTC, DemisRincon commented on FlightReservation/src/screens/SignUp.js
> +              </View>
Most of the inputs, title, and error text could be extracted as a component, tools of code improvement like CodeClimate will detect this as code repeated.
The rest of the code looks great.

2021-07-06 17:46 UTC, jkzasori requested changes
It's okay but... I think you could refactor FirebaseSignIn component because has a lot of code and with the time it will not be easy to support components with a lot of code also I think you can reuse code.

2021-07-06 19:08 UTC, DemisRincon requested changes
Please review the recommendation, in general good!

2021-07-07 14:21 UTC, carloseag1609 commented
Thanks for the comments :) We'll refactor these inputs and texts in the next feature with the styles.

2021-07-07 15:10 UTC, DemisRincon approved these changes

2021-07-07 15:11 UTC, DemisRincon approved these changes

2021-07-07 15:11 UTC, DemisRincon approved these changes

2021-07-07 15:11 UTC, cortezroberto approved these changes
it's ok

2021-07-07 15:12 UTC, yovanha approved these changes
Good changes!

2021-07-07 15:14 UTC, merged