Form structure for Log in added.
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k05-t01 pull request #17
Opened 2021-07-08 19:23 UTC by cortezroberto

# Description
 -  We added the structure for the Log in form.
 - Fields and components creation.

2021-07-08 20:19 UTC, DemisRincon requested changes
Please review the request of changes

2021-07-08 20:19 UTC, DemisRincon commented on FlightReservation/src/screens/LogIn.js
> +      </Provider>
The use of the provider with the store should be global and used once please move the provider as a wrapper for the app in root/App.js provider also is present in signup.js (it should exist only an instance in the project) please read the redux documentation or ask for advice

2021-07-08 22:14 UTC, YilKanda reviewed
Try to use internalization instead of static texts.

You can make use of libraries like this:

[react-native-i18n](https://www.npmjs.com/package/react-native-i18n)

2021-07-08 22:14 UTC, YilKanda commented on FlightReservation/src/screens/LogIn.js
> +  };
If you can try to pass this function to a separate file, for example Validations.js, so as not to overload this component.

2021-07-08 22:14 UTC, YilKanda commented on FlightReservation/src/screens/LogIn.js
> +//   const [emailInUseError, setEmailInUseError] = useState(false);
If you don't occupy this line, delete it.

2021-07-08 22:14 UTC, YilKanda commented on FlightReservation/src/screens/LogIn.js
> +        {/* {emailInUseError && <Text>Email in use. Use a diferent email</Text>} */}
If you don't occupy this line, delete it.

2021-07-09 17:50 UTC, hancel-avila approved these changes
Nice work!

2021-07-09 19:39 UTC, YilKanda approved these changes
LGTM!

2021-07-09 19:42 UTC, DemisRincon approved these changes

2021-07-12 14:11 UTC, merged