#feature#10 log in form style
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k05-t01 pull request #27
Opened 2021-07-13 16:09 UTC by hancel-avila

# Description
What did you implemented/Why did you implemented this:
 - We stilyzed the LogIn screen with the colors previously declared. Why? The design will be uniformly stylized by the same app convention

![image](https://user-images.githubusercontent.com/61561709/125485004-dd816a6f-d76b-4ee9-b231-55d6efc893a8.png)

2021-07-13 17:08 UTC, cortezroberto submitted a review, later dismissed
Good work

2021-07-13 17:15 UTC, DemisRincon requested changes
Please read the recommendations for improvement most of them are inline styles please move that to an stylesheet document

2021-07-13 17:15 UTC, DemisRincon commented on FlightReservation/src/screens/SignUp.js
> +                      }}
Avoid inline styles

2021-07-13 17:15 UTC, DemisRincon commented on FlightReservation/src/screens/LogIn.js
> +            {/*  */}
delete this comment

2021-07-13 17:15 UTC, DemisRincon commented on FlightReservation/src/screens/LogIn.js
> +                }}
avoid inline styles

2021-07-13 17:15 UTC, DemisRincon commented on FlightReservation/src/screens/LogIn.js
> +                ]}>
avoid inline styles

2021-07-13 17:15 UTC, DemisRincon commented on FlightReservation/src/screens/LogIn.js
> +                  <Text style={{color: colors.white, fontSize: 18}}>
avoid inline styles

2021-07-13 17:15 UTC, DemisRincon commented on FlightReservation/src/screens/LogIn.js
> +                  <Text style={{color: 'blue'}}>Sign up</Text>
avoid inline styles

2021-07-13 17:15 UTC, DemisRincon commented on FlightReservation/src/screens/SignUp.js
>                    <Text style={{paddingTop: 20}}>
avoid inline styles

2021-07-13 17:15 UTC, DemisRincon commented on FlightReservation/src/screens/SignUp.js
> +                      {' '}
No need for this line

2021-07-13 22:52 UTC, YilKanda reviewed
As an added comment, I can recommend using internationalization instead of static text.

You can use this library, for example, to do this:

[react-native-i18n](https://www.npmjs.com/package/react-native-i18n)

2021-07-15 15:31 UTC, yovanha submitted a review, later dismissed
Good job!

2021-07-15 17:14 UTC, DemisRincon submitted a review, later dismissed

2021-07-15 20:42 UTC, jkzasori approved these changes

2021-07-16 14:11 UTC, cortezroberto approved these changes
LGTM!

2021-07-16 14:12 UTC, merged