#feature#11 login by verifying data in firebase
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k05-t01 pull request #33
Opened 2021-07-19 18:04 UTC by hancel-avila

# Description
 - We've initialized the Firebase authenticator.
 - We've implemented the logInWithEmailAndPassword method to handle the login with user's email and password.
 
 Examples:
 - If the user already has an account, he will be able to log in on the Log in screen. Firebase will make the email and password validation.
 - Why?: These changes complete the user login and account creation experienece.
 
 
 # Testing
You can create a new user on the **Sign up** screen filling the info required (name, email & password) with valid credentials and press enter. 
Then click on the **Log in** text, down below the Sign Up with Google button, it will send you to the Log in screen.
Enter the previous email and password on the correspondant inputs and press enter.

![image](https://user-images.githubusercontent.com/61561709/126205810-c3563147-38f5-467c-8079-3783c2a07939.png)

2021-07-19 22:09 UTC, DemisRincon requested changes
Check the comments

2021-07-19 22:09 UTC, DemisRincon commented on FlightReservation/src/helpers/authState.js
> +        <Text>Login</Text>
use the library I18n to put this messages

2021-07-19 22:09 UTC, DemisRincon commented on FlightReservation/src/helpers/authState.js
> +      <Text>Welcome {user.email}</Text>
use the library I18n to put this messages

2021-07-19 22:09 UTC, DemisRincon commented on FlightReservation/src/screens/LogIn.js
>          }}
use data from inputs to test the function read the documentation to use formik

2021-07-19 22:10 UTC, DemisRincon commented on FlightReservation/src/screens/LogIn.js
>          }}
also you have merge conflicts pleas pull your main branch and solve the conflicts

2021-07-20 18:48 UTC, DemisRincon approved these changes

2021-07-20 18:52 UTC, jkzasori approved these changes

2021-07-20 18:58 UTC, yovanha approved these changes
Good job!

2021-07-20 19:00 UTC, merged