Feature #16 Add styles on the text messages of the fields.
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k05-t01 pull request #39
Opened 2021-07-23 20:31 UTC by yovanha

# Description
 - We've added styles to the validation messages for the Sign Up and Log In screen.
 - We've implement a new function to detect if the user is putting its credentials wrong in the Log In screen.
 - We've edited the TextField component to alert the users in the Sign Up screen if the email added already exists.
 - We've edited each component to dissapear the error messages when the user made the correct implementation in both screens.
  
  ## Screenshots 
![image](https://user-images.githubusercontent.com/72411097/126836805-6197bed3-7e68-4475-a2ec-29ae7fe8d3dd.png)

2021-07-23 21:01 UTC, DemisRincon approved these changes

2021-07-23 21:42 UTC, cortezroberto submitted a review, later dismissed
Good

2021-07-24 01:00 UTC, YilKanda requested changes

2021-07-24 02:38 UTC, jkzasori approved these changes

2021-07-26 14:50 UTC, yovanha commented on FlightReservation/src/screens/LogIn.js
> +          password: 'Juan123%',
We implement them to make tests for the user Log In, but I will remove it and put it on my local repository.

2021-07-26 16:51 UTC, jkzasori approved these changes

2021-07-26 22:28 UTC, YilKanda approved these changes
LGTM!

2021-07-27 14:26 UTC, cortezroberto approved these changes
LGTM

2021-07-27 14:27 UTC, merged